name: Test - mitosheet frontend

on:
  push:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'
  pull_request:
    paths:
      - 'mitosheet/**'
      - 'tests/**'

jobs:
  test-mitosheet-frontend:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.6', '3.8', '3.10']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          mitosheet/setup.py
          tests/requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: mitosheet/package-lock.json
    - name: Install dependencies
      run: |
        cd tests
        bash dev-setup.sh
    - name: Start a server and run tests
      run: |
        cd tests
        source venv/bin/activate
        jupyter lab --config jupyter_server_test_config.py &
        jlpm playwright test --retries=3