name: Test mitosheet frontend

on:
  push:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'
      - 'tests/**'

jobs:
  test-mitosheet-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.6', '3.8', '3.10']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd tests
        bash dev-setup.sh
    - name: Start a server and run tests
      run: |
        cd tests
        npm install
        source venv/bin/activate
        jupyter lab --config jupyter_server_test_config.py &
        jlpm playwrite test