name: Test - mitosheet frontend

on:
  push:
    branches: [ dev ]
    paths:
      - 'mitosheet/**'
  pull_request:
    paths:
      - 'mitosheet/**'
      - 'tests/**'

jobs:
  test-mitosheet-frontend:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.6', '3.8', '3.10']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          mitosheet/setup.py
          tests/requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: mitosheet/package-lock.json
    - name: Install dependencies
      run: |
        cd tests
        bash dev-setup.sh
    - name: Start a server and run tests
      run: |
        cd tests
        source venv/bin/activate
        jupyter lab --config jupyter_server_test_config.py &
        npm run test:jupyterlab

  test-mitosheet-frontend-streamlit:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
        run_count: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          mitosheet/setup.py
          tests/requirements.txt
          tests/extra-requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: mitosheet/package-lock.json
    - name: Install dependencies
      run: |
        cd tests
        bash dev-setup.sh
        source venv/bin/activate
        pip install -r extra-requirements.txt
    - name: Start a server and run tests
      run: |
        cd tests
        source venv/bin/activate
        streamlit run streamlit-test.py --server.port 8555 &
        npm run test:streamlit
    - name: Upload test-results if failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: test-results
        retention-days: 14

  test-mitosheet-frontend-dash:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          mitosheet/setup.py
          tests/requirements.txt
          tests/extra-requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: mitosheet/package-lock.json
    - name: Install dependencies
      run: |
        cd tests
        bash dev-setup.sh
        source venv/bin/activate
        pip install -r extra-requirements.txt
    - name: Start a server and run tests
      run: |
        cd tests
        source venv/bin/activate
        python dash-test.py &
        npm run test:dash